# Generated by Django 6.0 on 2025-12-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Wellness', 'Wellness'), ('Lifestyle', 'Lifestyle'), ('Creative', 'Creative'), ('Fashion', 'Fashion'), ('Photography', 'Photography'), ('Time Management', 'Time Management'), ('Travel', 'Travel')], max_length=50),
        ),
    ]
